import type { Metadata, Viewport } from "next";
import "../globals.css";
import { ReactQueryProvider } from "@/context/reactQueryProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	interactiveWidget: "resizes-content",
	userScalable: false,
	maximumScale: 1,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			style={{ overscrollBehavior: "none" }}>
			<link
				rel="icon"
				href="./favicon.ico"
				type="image/x-icon"
			/>
			<body className={`antialiased font-urbanist`}>
				<ReactQueryProvider>{children}</ReactQueryProvider>
			</body>
		</html>
	);
}
